myclub_website/events/urls.py
from django.urls import path
from . import views

app_name = "events"
urlpatterns = [
	path("", views.home, name = "home"),
	path("<int:year>/<str:month>/", views.home, name = "home"),
	path("list_events/", views.list_events, name = "list_events"),
	path("add_venue", views.add_venue, name = "add_venue"),
	path("list_venues/", views.list_venues, name = "list_venues"),
	path("show_venue/<venue_id>", views.show_venue, name = "show_venue"),
	path("search_venue/", views.search_venue, name = "search_venue"),
	path("update_veneu/<venue_id>", views.update_venue, name = "update_venue"),
	path("delete_venue/<venue_id>/", views.delete_venue, name = "delete_venue"),
	path("add_event", views.add_event, name = "add_event"),
	path("update_event/<event_id>/", views.update_event, name = "update_event"),
	path("delete_event/<event_id>/", views.delete_event, name = "delete_event"),
	path('venue_text/', views.venue_text, name = "venue_text"),
	path('venue_csv/', views.venue_csv, name = "venue_csv"),
	path('my_events/', views.my_events, name = "my_events"),
	path('search_event/', views.search_event, name = "search_event"),
	path('admin_approval/', views.admin_approval, name = "admin_approval"),
	path('venue_events/<venue_id>/', views.venue_events, name = "venue_events"),
	path('show_event/<event_id>/', views.show_event, name = "show_event"),
]

myclub_website/myclub_website/urls.py
from django.contrib import admin
from django.urls import path, include
# for upload image
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('members/', include('django.contrib.auth.urls')), 
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = " "
admin.site.site_title = " "
admin.site.index_title = " "

myclub_website/events/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

class Venue(models.Model):
	name = models.CharField("Venue Name", max_length=120)
	address = models.CharField(max_length=300)
	zip_code = models.CharField("Zip Code", max_length=15)
	phone = models.CharField("Contact Phone", max_length=25)
	web = models.URLField("Website Address")
	email_address = models.EmailField("Email")
	# New Addition
	owner = models.IntegerField('Venue Owner', blank=False, default=1)
	venue_image = models.ImageField(null=True, blank=True, upload_to='images/')

	class Meta: # Go to admin site
		verbose_name_plural = ('Test')
		verbose_name = ('Postion')
		ordering = ('-name',)

	def __str__(self):
		return self.name

class MyClubUser(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	email = models.EmailField("User Email")

	def __str__(self):
		return self.first_name + ' ' + self.last_name	

class Event(models.Model):
	name = models.CharField("Event Name", max_length = 120)	
	event_date = models.DateTimeField("Event Date")
	# venue = models.CharField(max_length = 120)
	venue = models.ForeignKey(Venue, blank=True,null=True,on_delete=models.CASCADE)
	# manager = models.CharField(max_length = 60)
	manager = models.ForeignKey(User, blank = True, null = True, on_delete = models.SET_NULL)
	attendees = models.ManyToManyField(MyClubUser, blank=True)
	description = models.TextField(blank=True)
	approved = models.BooleanField('Approved', default=False)

	def __str__(self):
		return self.name

	@property
	def Days_till(self):
		today = date.today()
		days_till = self.event_date.date() - today
		days_till_stripped = str(days_till).split(",",1)[0]
		return days_till_stripped
	
	@property
	def Is_Past(self):
		today = date.today()
		if self.event_date.date() < today:
			thing = "Past"
		else:
			thing = "Future"
		return thing

	@property
	def datetime(self):
		date = self.event_date.date()
		today = date.today()
		pr = f''' .date : {date} || .today : {today} '''
		return pr

myclub_website/events/forms.py
from django import forms
from django.forms import ModelForm
from .models import Venue, Event


#Create a venue form
class VenueForm(ModelForm):
	class Meta:
		model = Venue 
		# fields = "__all__"
		# OR
		fields = (
			"name", 
			"address", 
			"zip_code", 
			"phone", 
			"web", 
			"email_address",
			"venue_image"
			)

		labels = {
			"name" : '',
			"address" : '',
			"zip_code" : '',
			"phone": '',
			"web": '',
			"email_address": '',
			"venue_image" : "",
		}

		widgets = {
			"name" : forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Venue Name'}),
			"address" : forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Address'}),
			"zip_code" : forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Zip Code'}),
			"phone": forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Phone'}),
			"web": forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Web Address'}),
			"email_address": forms.EmailInput(attrs = {'class' : 'form-control', 'placeholder' : 'Email'}),
		}


# Admin Superuser Event Form
class EventFormAdmin(ModelForm):
	class Meta:
		model = Event
		fields = ("__all__")
		labels = {
			"name" : "",
			"event_date": "YYYY-MM-DD HH:MM:SS:",
			"venue" : "Venue",
			"manager" : "Manager",
			"attendees" : "Attendees",
			"description" : "",
		}
		widgets = {
			"name" : forms.TextInput(attrs = {'class':'form-control','placeholder':'Event Name'}),
			"event_date": forms.DateInput(attrs = {'class':'form-control','placeholder':'Event Date'}),
			"venue" : forms.Select(attrs = {'class':'form-select','placeholder':'Venue'}),
			"manager" : forms.Select(attrs = {'class':'form-select','placeholder':'Manager'}),
			"attendees" : forms.SelectMultiple(attrs = {'class':'form-control','placeholder':'Attendees'}),
			"description" : forms.Textarea(attrs = {'class':'form-control','placeholder':'Description'}),
		}

# User Event Form (we delete manager input)
class EventForm(ModelForm):
	class Meta:
		model = Event
		fields = ("name", "event_date", "venue", "attendees", "description")
		labels = {
			"name" : "",
			"event_date": "YYYY-MM-DD HH:MM:SS:",
			"venue" : "Venue",
			"attendees" : "Attendees",
			"description" : "",
		}
		widgets = {
			"name" : forms.TextInput(attrs = {'class':'form-control','placeholder':'Event Name'}),
			"event_date": forms.DateInput(attrs = {'class':'form-control','placeholder':'Event Date'}),
			"venue" : forms.Select(attrs = {'class':'form-select','placeholder':'Venue'}),
			"attendees" : forms.SelectMultiple(attrs = {'class':'form-control','placeholder':'Attendees'}),
			"description" : forms.Textarea(attrs = {'class':'form-control','placeholder':'Description'}),
		}

myclub_website/events/views.py
from django.shortcuts import render, redirect
import calendar
from calendar import HTMLCalendar
from datetime import datetime
from .models import Event, Venue
from .forms import VenueForm, EventForm, EventFormAdmin
from django.http import HttpResponseRedirect, HttpResponse
import csv
from django.contrib.auth.models import User
from django.core.paginator import Paginator #(next-page) (preves-page)
from django.contrib import messages

# Create your views here.

def home(request, year = datetime.now().year, month = datetime.now().strftime('%B')):
	name = "Akmik"
	month = month.title() # or month.capitalize()
	# Convert month from name to number
	month_number = list(calendar.month_name).index(month)
	month_number = int(month_number)

	# create a calendar
	cal = HTMLCalendar().formatmonth(
			year,
			month_number
		)
	# Get current year
	now = datetime.now()
	current_year = now.year

	#Get current time
	time = now.strftime("%I:%M:%S %p")

	event_list = Event.objects.filter(
			event_date__year = 2022,
			event_date__month = 10
		)
	return render(request, "events/home.html", {
		"name" : name,
		"year" : year,
		"month" : month,
		"month_number" : month_number,
		"cal" : cal,
		"current_year" : current_year,
		"time" : time,
		"event_list" : event_list
		})

def show_venue(request, venue_id): # click on link venue
	venue = Venue.objects.get(pk=venue_id)
	venue_owner = User.objects.get(pk=venue.owner)
	
	# Grap the events from that venue
	events = venue.event_set.all()
	return render(request, "events/show_venue.html",{	
		"venue" : venue,
		"venue_owner" : venue_owner,
		'events' : events
		})

def search_venue(request): # click search
	if request.method == "POST":
		searched = request.POST.get("searched")
		venues = Venue.objects.filter(name__contains=searched)
		return render(request, "events/search_venue.html", {
			"searched" : searched,
			"venues" : venues
			})
	else:
		return render(request, "events/search_venue.html", {

			})


def add_venue(request):
	submitted = False
	if request.method == "POST":
		form = VenueForm(request.POST, request.FILES) #get the information add pass it to VenueFrom
		if form.is_valid():
			venue = form.save(commit=False)
			venue.owner = request.user.id
			venue.save()
			return HttpResponseRedirect('/add_venue?submitted=True')
	else:
		form = VenueForm
		if "submitted" in request.GET:
			submitted = True

	return render(request, 'events/add_venue.html',{
			"form" : form,
			"submitted" : submitted
		})

def update_venue(request, venue_id):
	venue = Venue.objects.get(pk=venue_id)
	form = VenueForm(request.POST or None, request.FILES or None, instance=venue)
	if form.is_valid():
		form.save()
		return redirect('/list_venues/')#from urls.py
	return render(request, "events/update_venue.html",{
		"venue" : venue,
		"form" : form,
		})

def list_venues(request):
	#set up pagination
	p = Paginator(Venue.objects.all(), 2)
	page = request.GET.get('page')
	venues = p.get_page(page)
	nums = 'a' * venues.paginator.num_pages

	return render(request, "events/venue.html",{
		'venues' : venues,
		'nums' : nums
		})

def delete_venue(request, venue_id):
	venue = Venue.objects.get(pk=venue_id)
	venue.delete()
	return redirect('/list_venues/')


def add_event(request):
	submitted = False
	if request.method == "POST":
		if request.user.is_superuser:
			form = EventFormAdmin(request.POST) #get the information add pass it to VenueFrom
		else:
			form = EventForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/add_event?submitted=True')
	else:
		# Just Going To The Page, Not Submitting
		if request.user.is_superuser:
			form = EventFormAdmin
		else:
			form = EventForm
		if "submitted" in request.GET:
			submitted = True

	return render(request, 'events/add_event.html',{
			"form" : form,
			"submitted" : submitted
		})

def update_event(request, event_id):
	event = Event.objects.get(pk=event_id)
	form = EventForm(request.POST or None, instance=event)
	if form.is_valid():
		form.save()
		return redirect('/list_events/')# name from urls.py
	return render(request, "events/update_event.html",{
		"event" : event,
		"form" : form,
		})

def list_events(request):
	event_list = Event.objects.all().order_by('?')
	return render(request, "events/events_list.html", {
		"event_list" : event_list
		})

def delete_event(request, event_id):
	event = Event.objects.get(pk=event_id)
	if request.user == event.manager:
		event.delete()
	else:
		messages.success(request, ("You don't have permition"))

	return redirect('/list_events/')


def venue_text(request):
	response = HttpResponse(content_type='text/plain')
	response['Content-Disposition'] = 'attachment; filename=venues.txt'
	venues = Venue.objects.all()

	lines = []
	for venue in venues:
		lines.append(f'{venue.name}\n{venue.address}\n{venue.zip_code}\n{venue.phone}\n{venue.web}\n{venue.email_address}\n\n')

	response.writelines(lines)
	return response

def venue_csv(request):
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename=venues.csv'

	# create a csv writer
	writer = csv.writer(response)

	# Add column headings to the csv file
	writer.writerow(['Venue Name', 'Address', 'Zip_Code', 'Phone', 'Web', 'Email_Address'])

	venues = Venue.objects.all()

	for venue in venues:
		writer.writerow([venue.name, venue.address, venue.zip_code, venue.phone, venue.web, venue.email_address])

	return response

def my_events(request):
	if request.user.is_authenticated:
		me = request.user.id
		events = Event.objects.filter(attendees=me)
		return render(request, "events/my_events.html", {
			"events" : events
			})

	else:
		messages.success(request, ("Your don't logied in!!!"))
		return redirect('events:home')

def search_event(request):
	searched = request.POST.get("searched")
	events = Event.objects.filter(name__contains=searched)
	return render(request, "events/search_event.html", {
		'searched' : searched,
		'events' : events
		})

def admin_approval(request):
	# Get The Venues
	venue_list = Venue.objects.all()
	# Get Counts
	event_count = Event.objects.all().count()
	venue_count = Venue.objects.all().count()
	user_count = User.objects.all().count()

	event_list = Event.objects.all().order_by('-event_date')
	if request.user.is_superuser:
		if request.method == 'POST':
			id_list = request.POST.getlist('boxes') # boxes is name of checkbox in admin_approval.html
			#Uncheck all events
			event_list.update(approved=False)

			# Update the datebase
			for x in id_list:
				Event.objects.filter(pk=int(x)).update(approved=True)
			messages.success(request, ("Event List Approval Has been Approvaled"))
			return redirect('events:list_events')
		else:
			return render(request, 'events/admin_approval.html', {
				'event_list' : event_list,
				'event_count' : event_count,
				'venue_count' : venue_count,
				'user_count' : user_count,
				'venue_list' : venue_list,
				})
	else:
		messages.success(request, ("You aren't authorized to view this page!"))
		return redirect('events:home')

	return render(request, 'events/admin_approval.html', {
		
		})

#Show Events In A Venue
def venue_events(request, venue_id):
	# Grab the venue
	venue = Venue.objects.get(pk=venue_id)
	# Grab the events from that venue
	events = venue.event_set.all() # There is a relationship via Foriegn Key

	if events:
		return render(request, 'events/venue_events.html', {
			'events' : events
			})
	else:
		messages.success(request, ("That Venue Has No Events At This Time..."))
		return redirect('events:admin_approval')

# Show Event
def show_event(request, event_id):
	event = Event.objects.get(pk=event_id)
	return render(request, 'events/show_event.html', {
		'event': event
		})

myclub_website/events/templates/events/add_event.html
{% extends 'events/layout.html' %}

{% block body %}
		{% if user.is_authenticated %}
		<h1>Add Event To Database</h1>
		<br><br>
		{% if submitted %}
			Your Event Was Submited Succefully!!!
		{% else %}
			<form action="" method="POST">
				{% csrf_token %}
				{{ form.as_p}}
				<input type="submit" value="Submit" class="btn btn-secondary">
			</form>
		{% endif %}
		{% else %}
			<h1>Sorry you have to login ☺</h1>
			<a href="{% url 'login' %}">Login</a>
		{% endif %}

{% endblock %}

myclub_website/events/templates/events/add_venue.html
{% extends 'events/layout.html' %}

{% block body %}
		{% if user.is_authenticated %}
	<center>
			<h1>Add Venue To Database</h1>
			ID : {{ user.id }}
			<br><br>
			{% if submitted %}
				Your Venue Was Submited Succefully!!!
			{% else %}
				<form action="" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.as_p}}
					<input type="submit" value="Submit" class="btn btn-secondary">
				</form>
			{% endif %}
	</center>
		{% else %}
			<h1>Sorry you have to login ☺</h1>
			<a class="btn btn-outline-secondary" href="{% url 'login' %}">Login</a>
		{% endif %}

{% endblock %}

myclub_website/events/templates/events/events_list.html
{% extends 'events/layout.html' %}

{% block body %}

	<h1>Events List</h1>
		{% for event in event_list %}
		{% if event.approved %}

		<div class="card">
  			<div class="card-header">{{ event }}</div>
  			<div class="card-body">
    			<h5 class="card-title">Venue: {{ event.venue }}</h5>
    			<p class="card-text">	
					<ul>
						<li>Date: {{ event.event_date }}</li>
						<li>Days_till : {{ event.Days_till }}</li>
						<li>Occured: {{ event.Is_Past }}</li>
						<li>Datetime : {{ event.datetime }}</li>
						<li>Venue Phone: {{ event.venue.phone }}</li>
						<li>{{ event.id }}</li>
						<li>Manager: {{ event.manager }}</li>
						<li>Description: {{ event.description }}</li>
						<li>Approved: {{ event.approved }}
						<li>Attendees:
							{% for attend in event.attendees.all %}
								&nbsp<br>{{ attend }}
							{% endfor %}
						</li>
					</ul>
    			</p>
    			<a href="#" class="btn btn-primary">Go somewhere</a>
  			</div>
			{% if user.is_authenticated %}
				{% if user == event.manager %}
		  			<div class="card-footer text-muted">
		  				<a class="btn btn-outline-secondary btn-sm" href="{% url 'events:update_event' event.id %}">Update Event</a>
		  				<a class="btn btn-outline-danger btn-sm" href="{% url 'events:delete_event' event.id %}">Delete Event</a>
		  			</div>
	  			{% endif %}
  			{% endif %}
		</div>
		<br>


		{% endif %}
		{% endfor %}

{% endblock %}

myclub_website/events/templates/events/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'events:home' %}">{{user}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events:home' '2023' 'March' %}">March</a>
        </li>

         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Events
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'events:list_events' %}">Events</a></li>
            <li><a class="dropdown-item" href="{% url 'events:search_event' %}">Search For Event</a></li>
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'events:add_event' %}">Add Events</a></li>
            <li><a class="dropdown-item" href="{% url 'events:my_events' %}">My Events</a></li>
            {% endif %}
          </ul>
        </li>

         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Venue
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'events:list_venues' %}">Venues</a></li>
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'events:add_venue' %}">Add Venue</a></li>
            {% endif %}
          </ul>
        </li>

         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Downloads
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'events:venue_csv' %}">Venue Csv</a></li>
            <li><a class="dropdown-item" href="{% url 'events:venue_text' %}">Venue Text</a></li>
          </ul>
        </li>


        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events:admin_approval' %}">Admin</a>
        </li>
        {% endif %}
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register_user' %}">Register</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>

        {% endif %}

      </ul>
      <form class="d-flex" role="search" method="POST" action="{% url 'events:search_venue' %}">
        {% csrf_token %}
        <input class="form-control me-2" name="searched" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

myclub_website/events/templates/events/search_event.html
{% extends 'events/layout.html' %}

{% block body %}

		<div style="margin-bottom: 5px;" class="card">
  			{% if searched %}
  				<div class="card-header"><h2>Search For {{ searched }}</h2></div>
  			{% else %}
  				<div class="card-header"><h2>Search</h2></div>
  			{% endif %}
  			<div class="card-body">
		        <form class="d-flex" role="search" method="POST" action="{% url 'events:search_event' %}">
			        {% csrf_token %}
			        <input class="form-control me-2" name="searched" type="search" placeholder="Search" aria-label="Search">
			        <button class="btn btn-outline-secondary" type="submit">Search</button>
		        </form>
  			</div>
		</div>
				{% if searched %}
					{% for event in events %}
					<div class="card">
			  			<div class="card-header">{{ event }}</div>
			  			<div class="card-body">
			    			<h5 class="card-title">Venue: {{ event.venue }}</h5>
			    			<p class="card-text">	
								<ul>
									<li>Date: {{ event.event_date }}</li>
									<li>Venue Phone: {{ event.venue.phone }}</li>
									<li>{{ event.id }}</li>
									<li>Manager: {{ event.manager }}</li>
									<li>Description: {{ event.description }}</li>
									<li>Attendees:
										{% for attend in event.attendees.all %}
											&nbsp<br>{{ attend }}
										{% endfor %}
									</li>
								</ul>
			    			</p>
			    			<a href="#" class="btn btn-primary">Go somewhere</a>
			  			</div>
						{% if user.is_authenticated %}
							{% if user == event.manager %}
					  			<div class="card-footer text-muted">
					  				<a class="btn btn-outline-secondary btn-sm" href="{% url 'events:update_event' event.id %}">Update Event</a>
					  				<a class="btn btn-outline-danger btn-sm" href="{% url 'events:delete_event' event.id %}">Delete Event</a>
					  			</div>
				  			{% endif %}
			  			{% endif %}
					</div>
					{% endfor %}
				{% endif %}

{% endblock %}

myclub_website/events/templates/events/show_event.html
{% extends 'events/layout.html' %}

{% block body %}

<h1>Show Event</h1>
<br>
		{% if event.approved %}

		<div class="card">
  			<div class="card-header">{{ event }}</div>
  			<div class="card-body">
    			<h5 class="card-title">Venue: {{ event.venue }}</h5>
    			<p class="card-text">	
					<ul>
						<li>Date: {{ event.event_date }}</li>
						<li>Days_till : {{ event.Days_till }}</li>
						<li>Occured: {{ event.Is_Past }}</li>
						<li>Datetime : {{ event.datetime }}</li>
						<li>Venue Phone: {{ event.venue.phone }}</li>
						<li>{{ event.id }}</li>
						<li>Manager: {{ event.manager }}</li>
						<li>Description: {{ event.description }}</li>
						<li>Approved: {{ event.approved }}
						<li>Attendees:
							{% for attend in event.attendees.all %}
								&nbsp<br>{{ attend }}
							{% endfor %}
						</li>
					</ul>
    			</p>
    			<a href="#" class="btn btn-primary">Go somewhere</a>
  			</div>
			{% if user.is_authenticated %}
				{% if user == event.manager %}
		  			<div class="card-footer text-muted">
		  				<a class="btn btn-outline-secondary btn-sm" href="{% url 'events:update_event' event.id %}">Update Event</a>
		  				<a class="btn btn-outline-danger btn-sm" href="{% url 'events:delete_event' event.id %}">Delete Event</a>
		  			</div>
	  			{% endif %}
  			{% endif %}
		</div>
		<br>


		{% endif %}

{% endblock %}

myclub_website/events/templates/events/show_venue.html
{% extends 'events/layout.html' %}

{% block body %}

	<div class="card">
  			<div class="card-header">venue</div>
  			<div class="card-body">
    			<h5 class="card-title">Venue: {{ venue }}</h5>
    			<p class="card-text">	
					<ul>
						<li>{{ venue.address }}</li>
						<li>{{ venue.zip_code }}</li>
						<li>{{ venue.phone }}</li>
						<li>{{ venue.email_address }}</li>
						<li>{{ venue.web }}</li>
						<li>owner: {{ venue_owner }}</li>
						<li>owner_email : {{ venue_owner.email }}</li>
					</ul>
					{% if venue.venue_image %}
					<img src="{{ venue.venue_image.url }}" style="width: 200px;">
					{% endif %}
    			</p><br>
    			<h3>Events At This Venue</h3>
    			{% if events %}
				{% for event in events %}
					<a href="{% url 'events:show_event' event.id %}">{{ event }}</a><br>
				{% endfor %}
				<br>
				{% else %}
				No Events Schelduled At This Time.
				{% endif %}
  			</div>
  			<br><br>
		</div>
		<br>

{% endblock %}

myclub_website/events/templates/events/update_venue.html
{% extends 'events/layout.html' %}

{% block body %}

	<h1>update venue</h1>
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Update" name="submit" class="btn btn-secondary">
	</form>

{% endblock %}

myclub_website/events/templates/events/venue.html
{% extends 'events/layout.html' %}

{% block body %}

	<h1 style="color:#888">Venue...</h1>
	<table class=" table table-striped table-bordered table-hover">
		{% for venue in venues %}
			<tr>
				<td>
					<a href="{% url 'events:show_venue' venue.id %}">{{ venue }}</a>
				</td>
				{% if user.is_authenticated %}
					
				<td align="right">
					<a class="btn btn-outline-secondary btn-sm" href="{% url 'events:update_venue' venue.id %}">Update</a>
  					<a class="btn btn-outline-danger btn-sm" href="{% url 'events:delete_venue' venue.id %}">Delete</a>
				</td>
				{% endif %}
			</tr>
		{% endfor %}
	</table>

	<nav aria-label="Page navigation example">
		  <ul class="pagination justify-content-center">

	{% if venues.has_previous %}  
		<li class="page-item"><a class="page-link" href="?page=1">&laquo First Page</a></li>
		<li class="page-item"><a class="page-link" href="?page={{ venues.previous_page_number }}">Previous</a></li>
	{% endif %}

	<!-- <li class="page-item disabled"><a class="page-link" href="#">Page {{ venues.number }} of {{ venues.paginator.num_pages}}</a></li><br> -->

	{% for i in nums %}
		<li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
	{% endfor %}

	{% if venues.has_next %}
		<li class="page-item"><a class="page-link" href="?page={{ venues.next_page_number }}">Next</a></li>
		<li class="page-item"><a class="page-link" href="?page={{ venues.paginator.num_pages }}">Last Page &raquo</a></li>
	{% endif %}

		  </ul>
	</nav>
{% endblock %}

myclub_website/events/templates/events/venue_events.html
{% extends 'events/layout.html' %}

{% block body %}

<h1>List Events</h1>

{% for event in events %}
	<a href="{% url 'events:show_event' event.id %}">{{ event }}</a><br>
{% endfor %}

{% endblock %}