test1/akmik/urls.py
from django.urls import path
from . import views


app_name = "akmik"
urlpatterns = [
	path("", views.home, name = "home"),
	path("akmik/<int:year>/<str:month>/", views.home, name = "home"),
	path("form/", views.form, name = "form"),
	path("information/", views.information, name = "information"),
]

test1/test1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("akmik.urls")),
]

test1/akmik/models.py
from django.db import models

# Create your models here.

class Information(models.Model):
	First_Name = models.CharField("First Name", max_length=50)
	Last_Name = models.CharField("Last Name", max_length=50)
	Email = models.EmailField("Email")
	Password = models.CharField("Password", max_length=50)
	Re_Password = models.CharField("Re_Password", max_length=50)

	def __str__(self):
		return f""" {self.First_Name} {self.Last_Name} {self.Password} """

test1/akmik/forms.py
from .models import Information
from django import forms
from django.forms import ModelForm

class InformationForm(ModelForm):
	class Meta:
		model = Information
		fields = (
		"First_Name",
		"Last_Name",
		"Email",
		"Password",
		"Re_Password"
			)
		labels = {
		"First_Name":"",
		"Last_Name":"",
		"Email":"",
		"Password":"",
		"Re_Password":""
		}
		widgets = {
		"First_Name": forms.TextInput(attrs = {'class':'form-control','placeholder':'Enter Your First_Name'}),
		"Last_Name": forms.TextInput(attrs = {'class':'form-control','placeholder':'Enter Your Last_Name'}),
		"Email":forms.EmailInput(attrs = {'class':'form-control','placeholder':'Enter Your Email'}),
		"Password":forms.PasswordInput(attrs = {'class':'form-control','placeholder':'Enter Your Password'}),
		"Re_Password":forms.PasswordInput(attrs = {'class':'form-control','placeholder':'Enter Your Re_Password'})
		}

test1/akmik/views.py
from django.shortcuts import render
from datetime import datetime
from .forms import InformationForm
from django.http import HttpResponseRedirect
from .models import Information

# Create your views here.
def home(request, year = datetime.now().year, month = datetime.now().strftime("%B")):
	name = "akmik"
	age = 23
	now = datetime.now()
	year = now.year
	month = now.month
	return render(request, "events/home.html",{
		"name" : name,
		"age" : age,
		"year" : year,
		"month" : month
		})

def form(request):
	submitted = False
	if request.method == "POST":
		form = InformationForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/form?submitted=True')
	else:
		form = InformationForm
		if "submitted" in request.GET:
			submitted = True

	return render(request, "events/forms.html",{
		"form" : form,
		"submitted" : submitted
		})

def information(request):
	info = Information.objects.all()
	count = 0
	return render(request,'events/information.html',{
		"information" : info,
		"count" : count
		})

test1/akmik/templates/events/forms.html
{% extends 'events/layout.html' %}
{% block body %}
	<center>
		{% if submitted %}
			Success
		{% else %}
	<h1>Add Information</h1>
	<form action="" method="POST">
		{% csrf_token %}
		
		{{form.as_p}}
		<input type="submit" value="submit" class="btn btn-secondary">
	</form>
		{% endif %}
	</center>

{% endblock %}

test1/akmik/templates/events/home.html
{% extends 'events/layout.html' %}
{% block body %}
	
	<h1>Hello {{ name }}</h1>
	<h2>year is {{ year }}</h2>
	<h2>month is {{ month }}</h2>

{% endblock %}

test1/akmik/templates/events/information.html
{% extends 'events/layout.html' %}
{% block body %}
	{% for person in information %}
		clint number: {{ count }}
		{{person.First_Name}}
		{{person.Last_Name}}
		{{person.Email}}
		{{person.Password}}<br>
	{% endfor %}

{% endblock %}

test1/akmik/templates/events/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    {% include 'events/navbar.html' %}
        <div class="container">
    {% block body %}
    {% endblock %}
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    }
  </body>
</html>

test1/akmik/templates/events/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'akmik:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'akmik:form' %}">forms</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'akmik:information' %}">information</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>